### ISSUE TITLE
TLS verification failed in e2eUtils.js

### ISSUE THREAD

**Issue by lung21** [RUAN0007/caliper-min#6]
### Description
Multiple client connection options have been commented out for non-TLS traffic.

### Expected behavior

Allow TLS traffic using certification

### References
https://github.com/RUAN0007/caliper-min/blob/b558ef128c8a39b8f5227b7ea1c28ebac8961537/src/fabric/e2eUtils.js#L632

**Comment by RUAN0007** [comment]
Resolved in #7
